home:
  path: /
  controller: MaxServ\App\Controller\IndexController::index

products:
  path: /products{trailingSlash}
  controller: MaxServ\App\Controller\ProductController::index
  requirements:
    trailingSlash: "/?" # trailing slashes are causing issues with the route matching, so I'm making it optional

product_show:
  path: /products/{id}{trailingSlash}
  controller: MaxServ\App\Controller\ProductController::show
  requirements:
    trailingSlash: "/?"